### PR TITLE
Fixed texturePaths sort

### PR DESCRIPTION
**Pull request by Cyeniia**
If there are several moresuits folders in the plugins folder, then sorting with the full file path won't work

### CODE REVIEW

**Comment by x753** [comment]
I'm a bit confused, could you provide an example of where this problem would occur? From what I can tell it's not possible to have duplicate paths.

**Comment by Cyeniia** [comment]
my folder structure looks like this
- plugins
  - x753-More_Suits
    - moresuits
  - mon-BasedSuits
    - moreplugins

It could happen that we have the same names there.
The main problem was actually that you can't really sort with different paths.

For example, we have these files:
- plugins\x753-More_Suits\moresuits\Glow.png
- plugins\x753-More_Suits\moresuits\Slayer.png
- plugins\x753-More_Suits\moresuits\Luigi.png
- plugins\mon-BasedSuits\moresuits\frieren.png
- plugins\mon-BasedSuits\moresuits\jump king.png
- plugins\mon-BasedSuits\moresuits\my personality.png

the old sorting would look like this:
- plugins\mon-BasedSuits\moresuits\frieren.png
- plugins\mon-BasedSuits\moresuits\jump king.png
- plugins\mon-BasedSuits\moresuits\my personality.png
- plugins\x753-More_Suits\moresuits\Glow.png
- plugins\x753-More_Suits\moresuits\Luigi.png
- plugins\x753-More_Suits\moresuits\Slayer.png

which is fine as long as everyone in the lobby has the folders like this, but if someone copies all the files to `plugins\x753-More_Suits\moresuits\`, then the sort order would be as follows:
- plugins\x753-More_Suits\moresuits\frieren.png
- plugins\x753-More_Suits\moresuits\Glow.png
- plugins\x753-More_Suits\moresuits\jump king.png
- plugins\x753-More_Suits\moresuits\Luigi.png
- plugins\x753-More_Suits\moresuits\my personality.png
- plugins\x753-More_Suits\moresuits\Slayer.png

and that ultimately ensures that when I and someone else put on the same suit, we see a different suit on the other person.

image
image

The first image shows the sorting with two `moresuits` folders and the second image shows the sorting with one folder or with the fixed version

**Comment by Cyeniia** [comment]
i have overcomplicated the whole thing. this also works and is much simpler

**Comment by x753** [comment]
That's much better than the previous code.
I think I'll end up addressing this issue with this in the next update:
assetPaths = assetPaths.OrderBy(Path.GetFileNameWithoutExtension).ThenBy(p => p).ToList();
texturePaths = texturePaths.OrderBy(Path.GetFileNameWithoutExtension).ThenBy(p => p).ToList();

**Pull request closed without merging**
